### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by veeti** [tbroyer/bullet#1]
Hi,

Bullet looks very handy. Any plans to make an actual release into Central now that Dagger 2.0 is out?

**Comment by tbroyer** [comment]
I could make an 0.1 release, but there are constructs supported by Dagger that Bullet doesn't support (component methods returning `Provider`, `Lazy` or `MembersInjector`, and subcomponents) so a 1.0 would have to wait.

**Comment by tbroyer** [comment]
Just released 0.1, should appear in Central soon.

**Comment by tbroyer** [comment]
FYI, just released .20 supporting (hopefully) all Dagger usecases (provider, lazy, members injector, and subcomponents).
